version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1483041354
layout:
  /navigation/:
    -
      - 'logo-9608 25'
      - 'menu-6409 75'
  /header/:
    -
      - position-slideshow
  /breadcrumbs/:
    -
      - position-breadcrumbs
  /services/:
    -
      - 'position-services-a 25'
      - 'position-services-b 25'
      - 'position-services-c 25'
      - 'position-services-d 25'
  /intro/:
    -
      - 'position-intro-a 25'
      - 'position-intro-b 25'
      - 'position-intro-c 25'
      - 'position-intro-d 25'
  /maintenance/:
    -
      - 'position-maintenance-a 25'
      - 'position-maintenance-b 25'
      - 'position-maintenance-c 25'
      - 'position-maintenance-d 25'
  /portfolio/:
    -
      - 'position-portfolio-a 25'
      - 'position-portfolio-b 25'
      - 'position-portfolio-c 25'
      - 'position-portfolio-d 25'
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - position-illustration-top-1300
          -
            - 'position-article-top-a 50'
            - 'position-article-top-b 50'
          -
            - system-content-1470
          -
            - 'position-article-bottom-a 50'
            - 'position-article-bottom-b 50'
          -
            - 'position-article-bottom-c 50'
            - 'position-article-bottom-d 50'
      -
        'sidebar 25':
          -
            - position-sidebar-1400
          -
            - position-sidebottom
  /quoteone/:
    -
      - position-quote-1
  /features/:
    -
      - 'position-features-a 25'
      - 'position-features-b 25'
      - 'position-features-c 25'
      - 'position-features-d 25'
  /quotetwo/:
    -
      - position-quote-2
  /utility/:
    -
      - 'position-utility-a 25'
      - 'position-utility-b 25'
      - 'position-utility-c 25'
      - 'position-utility-d 25'
  /quotethree/:
    -
      - position-quote-3
  /related/:
    -
      - 'position-related-a 25'
      - 'position-related-b 25'
      - 'position-related-c 25'
      - 'position-related-d 25'
  /mainbottom/:
    -
      - 'position-mainbottom-a 25'
      - 'position-mainbottom-b 25'
      - 'position-mainbottom-c 25'
      - 'position-mainbottom-d 25'
  /maps/:
    -
      - position-googlemaps
  /footer/:
    -
      - 'position-footer-a 25'
      - 'position-footer-b 25'
      - 'position-footer-c 50'
  /copyright/:
    -
      - 'copyright-7436 50'
      - 'horizontalmenu-9034 50'
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    title: Slider
    attributes:
      boxed: ''
      class: g-flushed
  breadcrumbs:
    type: section
    attributes:
      boxed: ''
  services:
    type: section
    attributes:
      boxed: ''
  intro:
    type: section
    attributes:
      boxed: ''
  maintenance:
    type: section
    attributes:
      boxed: ''
  portfolio:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  quoteone:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  quotetwo:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  quotethree:
    type: section
    attributes:
      boxed: ''
  related:
    type: section
    attributes:
      boxed: ''
  mainbottom:
    type: section
    attributes:
      boxed: ''
  maps:
    type: section
    title: Location
    attributes:
      boxed: ''
      class: g-flushed
  footer:
    attributes:
      boxed: ''
  copyright:
    type: section
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'V-Web Logo'
    block:
      class: vweb-logo
  menu-6409:
    title: 'V-Web Menu'
    block:
      class: vweb-menu
  position-slideshow:
    attributes:
      key: slideshow
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-services-a:
    attributes:
      key: services-a
  position-services-b:
    attributes:
      key: services-b
  position-services-c:
    attributes:
      key: services-c
  position-services-d:
    attributes:
      key: services-d
  position-intro-a:
    attributes:
      key: intro-a
  position-intro-b:
    attributes:
      key: intro-b
  position-intro-c:
    attributes:
      key: intro-c
  position-intro-d:
    attributes:
      key: intro-d
  position-maintenance-a:
    attributes:
      key: maintenance-a
  position-maintenance-b:
    attributes:
      key: maintenance-b
  position-maintenance-c:
    attributes:
      key: maintenance-c
  position-maintenance-d:
    attributes:
      key: maintenance-d
  position-portfolio-a:
    attributes:
      key: portfolio-a
  position-portfolio-b:
    attributes:
      key: portfolio-b
  position-portfolio-c:
    attributes:
      key: portfolio-c
  position-portfolio-d:
    attributes:
      key: portfolio-d
  position-illustration-top-1300:
    attributes:
      key: illustration-top-1300
  position-article-top-a:
    attributes:
      key: article-top-a
  position-article-top-b:
    attributes:
      key: article-top-b
  position-article-bottom-a:
    attributes:
      key: article-bottom-a
  position-article-bottom-b:
    attributes:
      key: article-bottom-b
  position-article-bottom-c:
    attributes:
      key: article-bottom-c
  position-article-bottom-d:
    attributes:
      key: article-bottom-d
  position-sidebar-1400:
    attributes:
      key: sidebar-1400
  position-sidebottom:
    attributes:
      key: sidebottom
  position-quote-1:
    attributes:
      key: quote-1
  position-features-a:
    attributes:
      key: features-a
  position-features-b:
    attributes:
      key: features-b
  position-features-c:
    attributes:
      key: features-c
  position-features-d:
    attributes:
      key: features-d
  position-quote-2:
    attributes:
      key: quote-2
  position-utility-a:
    attributes:
      key: utility-a
  position-utility-b:
    attributes:
      key: utility-b
  position-utility-c:
    attributes:
      key: utility-c
  position-utility-d:
    attributes:
      key: utility-d
  position-quote-3:
    attributes:
      key: quote-3
  position-related-a:
    attributes:
      key: related-a
  position-related-b:
    attributes:
      key: related-b
  position-related-c:
    attributes:
      key: related-c
  position-related-d:
    attributes:
      key: related-d
  position-mainbottom-a:
    attributes:
      key: mainbottom-a
  position-mainbottom-b:
    attributes:
      key: mainbottom-b
  position-mainbottom-c:
    attributes:
      key: mainbottom-c
  position-mainbottom-d:
    attributes:
      key: mainbottom-d
  position-googlemaps:
    attributes:
      key: googlemaps
  position-footer-a:
    attributes:
      key: footer-a
  position-footer-b:
    attributes:
      key: footer-b
  position-footer-c:
    attributes:
      key: footer-c
  horizontalmenu-9034:
    title: 'Horizontal Menu'
    attributes:
      items:
        -
          text: 'Algemene Voorwaarden'
          link: /algemene-voorwaarden
          name: 'Algemene Voorwaarden'
        -
          text: 'Privacy Policy'
          link: /privacy-policy
          name: 'Privacy Policy'
        -
          text: 'Cookie Policy'
          link: /cookie-policy
          name: 'Cookie Policy'
