name: _error
timestamp: 1478779061
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1478601969
positions:
  services-b: Services-b
  services-c: Services-c
  services-d: Services-d
  intro-a: Intro-a
  intro-b: Intro-b
  intro-c: Intro-c
  intro-d: Intro-d
  maintenance-a: Maintenance-a
  maintenance-b: Maintenance-b
  maintenance-c: Maintenance-c
  maintenance-d: Maintenance-d
  portfolio-a: Portfolio-a
  portfolio-b: Portfolio-b
  portfolio-c: Portfolio-c
  portfolio-d: Portfolio-d
  illustration-top-1300: Illustration-top-1300
  article-top-a: Article-top-a
  article-top-b: Article-top-b
  article-bottom-a: Article-bottom-a
  article-bottom-b: Article-bottom-b
  article-bottom-c: Article-bottom-c
  article-bottom-d: Article-bottom-d
  sidebar-1400: Sidebar-1400
  sidebottom: Sidebottom
  googlemaps: Googlemaps
  quote-1: Quote-1
  features-a: Features-a
  features-b: Features-b
  features-c: Features-c
  features-d: Features-d
  quote-2: Quote-2
  utility-a: Utility-a
  utility-b: Utility-b
  utility-c: Utility-c
  utility-d: Utility-d
  quote-3: Quote-3
  mainbottom-a: Mainbottom-a
  mainbottom-b: Mainbottom-b
  mainbottom-c: Mainbottom-c
  mainbottom-d: Mainbottom-d
  footer-a: Footer-a
  footer-b: Footer-b
  footer-c: Footer-c
sections:
  navigation: Navigation
  breadcrumbs: Breadcrumbs
  services: Services
  intro: Intro
  maintenance: Maintenance
  portfolio: Portfolio
  maps: Location
  quote1: Quote1
  features: Features
  quote2: Quote2
  utility: Utility
  quote3: Quote3
  mainbottom: Mainbottom
  copyright: Copyright
  header: Slider
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9608: 'V-Web Logo'
  menu:
    menu-6409: 'V-Web Menu'
  position:
    position-services-b: Services-b
    position-services-c: Services-c
    position-services-d: Services-d
    position-intro-a: Intro-a
    position-intro-b: Intro-b
    position-intro-c: Intro-c
    position-intro-d: Intro-d
    position-maintenance-a: Maintenance-a
    position-maintenance-b: Maintenance-b
    position-maintenance-c: Maintenance-c
    position-maintenance-d: Maintenance-d
    position-portfolio-a: Portfolio-a
    position-portfolio-b: Portfolio-b
    position-portfolio-c: Portfolio-c
    position-portfolio-d: Portfolio-d
    position-illustration-top-1300: Illustration-top-1300
    position-article-top-a: Article-top-a
    position-article-top-b: Article-top-b
    position-article-bottom-a: Article-bottom-a
    position-article-bottom-b: Article-bottom-b
    position-article-bottom-c: Article-bottom-c
    position-article-bottom-d: Article-bottom-d
    position-sidebar-1400: Sidebar-1400
    position-sidebottom: Sidebottom
    position-googlemaps: Googlemaps
    position-quote-1: Quote-1
    position-features-a: Features-a
    position-features-b: Features-b
    position-features-c: Features-c
    position-features-d: Features-d
    position-quote-2: Quote-2
    position-utility-a: Utility-a
    position-utility-b: Utility-b
    position-utility-c: Utility-c
    position-utility-d: Utility-d
    position-quote-3: Quote-3
    position-mainbottom-a: Mainbottom-a
    position-mainbottom-b: Mainbottom-b
    position-mainbottom-c: Mainbottom-c
    position-mainbottom-d: Mainbottom-d
    position-footer-a: Footer-a
    position-footer-b: Footer-b
    position-footer-c: Footer-c
  custom:
    custom-8693: 'Custom HTML'
  copyright:
    copyright-8211: Copyright
  horizontalmenu:
    horizontalmenu-9034: 'Horizontal Menu'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
inherit: {  }
