
INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Klant','com_vwebadmin.klant','{"special":{"dbtable":"#__vwebadmin_customers","key":"id","type":"Klant","prefix":"VwebadminTable"}}', '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/klant.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_vwebadmin.klant')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Klant', 
	`table` = '{"special":{"dbtable":"#__vwebadmin_customers","key":"id","type":"Klant","prefix":"VwebadminTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/klant.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_vwebadmin.klant');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Website','com_vwebadmin.website','{"special":{"dbtable":"#__vwebadmin_websites","key":"id","type":"Website","prefix":"VwebadminTable"}}', '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/website.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"owner","targetTable":"#__vwebadmin_customers","targetColumn":"related_user_account","displayColumn":"company_name"},{"sourceColumn":"cms_guess","targetTable":"#__vwebadmin_website_cms","targetColumn":"id","displayColumn":"cms"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_vwebadmin.website')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Website', 
	`table` = '{"special":{"dbtable":"#__vwebadmin_websites","key":"id","type":"Website","prefix":"VwebadminTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/website.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"owner","targetTable":"#__vwebadmin_customers","targetColumn":"related_user_account","displayColumn":"company_name"},{"sourceColumn":"cms_guess","targetTable":"#__vwebadmin_website_cms","targetColumn":"id","displayColumn":"cms"}]}'
WHERE (`type_alias` = 'com_vwebadmin.website');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'CMS Type','com_vwebadmin.cmstype','{"special":{"dbtable":"#__vwebadmin_website_cms","key":"id","type":"Cmstype","prefix":"VwebadminTable"}}', '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/cmstype.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_vwebadmin.cmstype')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'CMS Type', 
	`table` = '{"special":{"dbtable":"#__vwebadmin_website_cms","key":"id","type":"CMS Type","prefix":"VwebadminTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/cmstype.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_vwebadmin.cmstype');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'CMS Versie','com_vwebadmin.cmsversie','{"special":{"dbtable":"#__vwebadmin_website_cms_version","key":"id","type":"Cmsversie","prefix":"VwebadminTable"}}', '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/cmsversie.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"cms","targetTable":"#__vwebadmin_website_cms","targetColumn":"id","displayColumn":"cms"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_vwebadmin.cmsversie')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'CMS Versie', 
	`table` = '{"special":{"dbtable":"#__vwebadmin_website_cms_version","key":"id","type":"CMS Versie","prefix":"VwebadminTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/cmsversie.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"cms","targetTable":"#__vwebadmin_website_cms","targetColumn":"id","displayColumn":"cms"}]}'
WHERE (`type_alias` = 'com_vwebadmin.cmsversie');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Onderhoud','com_vwebadmin.onderhoud','{"special":{"dbtable":"#__vwebadmin_maintenance","key":"id","type":"Onderhoud","prefix":"VwebadminTable"}}', '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/onderhoud.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"website","targetTable":"#__vwebadmin_websites","targetColumn":"id","displayColumn":"website"},{"sourceColumn":"package","targetTable":"#__vwebadmin_maintenance_package","targetColumn":"id","displayColumn":"package_name"},{"sourceColumn":"cms","targetTable":"#__vwebadmin_website_cms","targetColumn":"id","displayColumn":"cms"},{"sourceColumn":"cms_version","targetTable":"#__vwebadmin_website_cms_version","targetColumn":"id","displayColumn":"version"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_vwebadmin.onderhoud')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Onderhoud', 
	`table` = '{"special":{"dbtable":"#__vwebadmin_maintenance","key":"id","type":"Onderhoud","prefix":"VwebadminTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/onderhoud.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"website","targetTable":"#__vwebadmin_websites","targetColumn":"id","displayColumn":"website"},{"sourceColumn":"package","targetTable":"#__vwebadmin_maintenance_package","targetColumn":"id","displayColumn":"package_name"},{"sourceColumn":"cms","targetTable":"#__vwebadmin_website_cms","targetColumn":"id","displayColumn":"cms"},{"sourceColumn":"cms_version","targetTable":"#__vwebadmin_website_cms_version","targetColumn":"id","displayColumn":"version"}]}'
WHERE (`type_alias` = 'com_vwebadmin.onderhoud');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'onderhoudspakket','com_vwebadmin.onderhoudspakket','{"special":{"dbtable":"#__vwebadmin_maintenance_package","key":"id","type":"Onderhoudspakket","prefix":"VwebadminTable"}}', '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/onderhoudspakket.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_vwebadmin.onderhoudspakket')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'onderhoudspakket', 
	`table` = '{"special":{"dbtable":"#__vwebadmin_maintenance_package","key":"id","type":"onderhoudspakket","prefix":"VwebadminTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/onderhoudspakket.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_vwebadmin.onderhoudspakket');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Hosting','com_vwebadmin.hosting','{"special":{"dbtable":"#__vwebadmin_hosting","key":"id","type":"Hosting","prefix":"VwebadminTable"}}', '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/hosting.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"website","targetTable":"#__vwebadmin_websites","targetColumn":"id","displayColumn":"website"},{"sourceColumn":"package","targetTable":"#__vwebadmin_hosting_package","targetColumn":"id","displayColumn":"package_name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_vwebadmin.hosting')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Hosting', 
	`table` = '{"special":{"dbtable":"#__vwebadmin_hosting","key":"id","type":"Hosting","prefix":"VwebadminTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/hosting.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"website","targetTable":"#__vwebadmin_websites","targetColumn":"id","displayColumn":"website"},{"sourceColumn":"package","targetTable":"#__vwebadmin_hosting_package","targetColumn":"id","displayColumn":"package_name"}]}'
WHERE (`type_alias` = 'com_vwebadmin.hosting');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Pakket','com_vwebadmin.pakket','{"special":{"dbtable":"#__vwebadmin_hosting_package","key":"id","type":"Pakket","prefix":"VwebadminTable"}}', '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/pakket.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_vwebadmin.pakket')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Pakket', 
	`table` = '{"special":{"dbtable":"#__vwebadmin_hosting_package","key":"id","type":"Pakket","prefix":"VwebadminTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/pakket.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_vwebadmin.pakket');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Domein','com_vwebadmin.domein','{"special":{"dbtable":"#__vwebadmin_domains","key":"id","type":"Domein","prefix":"VwebadminTable"}}', '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/domein.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"website","targetTable":"#__vwebadmin_websites","targetColumn":"id","displayColumn":"website"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_vwebadmin.domein')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Domein', 
	`table` = '{"special":{"dbtable":"#__vwebadmin_domains","key":"id","type":"Domein","prefix":"VwebadminTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_vwebadmin\/models\/forms\/domein.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"website","targetTable":"#__vwebadmin_websites","targetColumn":"id","displayColumn":"website"}]}'
WHERE (`type_alias` = 'com_vwebadmin.domein');
